# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, max_length=1024, null=True, upload_to='story_pics')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='event_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='storymaker.Event'),
        ),
        migrations.AddField(
            model_name='choice',
            name='event_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='storymaker.Event'),
        ),
    ]
