# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('stats', jsonfield.fields.JSONField(blank=True, default={})),
                ('status', jsonfield.fields.JSONField(blank=True, default={})),
                ('items', jsonfield.fields.JSONField(blank=True, default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('visible_if', models.TextField()),
                ('sucess_if', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('cover', models.ImageField(max_length=1024, upload_to='story_picrures')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storymaker.Picture')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storymaker.Event')),
                ('world_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storymaker.Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storymaker.Picture'),
        ),
        migrations.AddField(
            model_name='choice',
            name='event_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='storymaker.Event'),
        ),
        migrations.AddField(
            model_name='choice',
            name='fail_event_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storymaker.Event'),
        ),
        migrations.AddField(
            model_name='choice',
            name='success_event_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storymaker.Event'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_here', to='storymaker.Event'),
        ),
        migrations.AddField(
            model_name='character',
            name='last_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storymaker.Event'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='storymaker.Story'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
