# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:30
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storymaker', '0004_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='items',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='character',
            name='stats',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
